CREATE TABLE IF NOT EXISTS user_food_consumption (
UserId INT NULL,
Foods VARCHAR(255) NULL,
emission FLOAT NULL,
categoryName VARCHAR(255) NULL,
date_of_entry TIMESTAMP NULL,
ObjectID INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ObjectID)
);